import type { Shooting } from "@/types/shooting";

export const demoShootings: Shooting[] = [
  {
    date: "2026-08-06",
    athlete: "Loan Cueto",
    sport: "Tennis",
    type: "Portrait Premium",
    place: "Fribourg",
    objective: "Renouveler le stock Premium",
    photographer: "Sébastien Mory",
    status: "Planifié",
    photos: 0,
    videos: 0,
    lightroomLink: "",
    driveLink: "",
    clientGalleryLink: "",
    instagramLink: "",
    shootingDone: false,
    importDone: false,
    backupDone: false,
    sortDone: false,
    retouchDone: false,
    exportDone: false,
    driveDone: false,
    publishedInstagram: false,
    publishedFacebook: false,
    publishedLinkedIn: false,
    published: false,
    deliverableClub: false,
    deliverableAthlete: false,
    deliverableSponsor: false,
    deliverableMedia: false,
    deliverableAgency: false,
    deliverableOther: false,
    notes: "",
  },
  {
    date: "2026-08-02",
    athlete: "Anastacia Fischer",
    sport: "Badminton",
    type: "Lifestyle",
    place: "Fribourg",
    objective: "Communication camp",
    photographer: "Sébastien Mory",
    status: "Réalisé",
    photos: 128,
    videos: 8,
    lightroomLink: "",
    driveLink: "",
    clientGalleryLink: "",
    instagramLink: "",
    shootingDone: true,
    importDone: true,
    backupDone: false,
    sortDone: false,
    retouchDone: false,
    exportDone: false,
    driveDone: false,
    publishedInstagram: false,
    publishedFacebook: false,
    publishedLinkedIn: false,
    published: false,
    deliverableClub: false,
    deliverableAthlete: false,
    deliverableSponsor: false,
    deliverableMedia: false,
    deliverableAgency: false,
    deliverableOther: false,
    notes: "",
  },
];
