import type { Athlete } from "@/types/athlete";

export const demoAthletes: Athlete[] = [
  {
    key: "anastacia-fischer",
    name: "Anastacia Fischer",
    initials: "AF",
    sport: "Badminton",
    club: "BC Fribourg",
    status: "Actif",
    lastShoot: "02.08.2026",
    media: 128,
    premium: 18,
    coverage: 82,
    tone: "solid",
    instagram: "@_anastacia.fischer_",
    email: "anastaciafischer@gmail.com",
    phone: "078 696 24 93",
    nextAction: "Préparer la story du camp en Malaisie",
    objective: "Intégrer le top 100 mondial",
    longTerm: "Participer aux Jeux olympiques",
  },
  {
    key: "loan-cueto",
    name: "Loan Cueto",
    initials: "LC",
    sport: "Tennis",
    club: "Tennis Club Bulle",
    status: "Actif",
    lastShoot: "18.03.2026",
    media: 286,
    premium: 4,
    coverage: 48,
    tone: "fragile",
    instagram: "@cuetoloan",
    email: "loan.cueto@icloud.com",
    phone: "+41 79 206 08 10",
    nextAction: "Programmer un shooting Premium",
    objective: "Progresser au classement national",
    longTerm: "Développer un projet sportif professionnel",
  },
  {
    key: "mila-benjak",
    name: "Mila Benjak",
    initials: "MB",
    sport: "Basketball",
    club: "Elfic Fribourg",
    status: "Actif",
    lastShoot: "25.03.2026",
    media: 194,
    premium: 12,
    coverage: 69,
    tone: "correct",
    instagram: "@mila.benjak",
    email: "milabenjak@gmail.com",
    phone: "+41 76 345 04 78",
    nextAction: "Préparer une interview portrait",
    objective: "Prendre un rôle important avec Elfic",
    longTerm: "Évoluer au plus haut niveau suisse",
  },
  {
    key: "aggee-wenzi",
    name: "Aggee Wenzi",
    initials: "AW",
    sport: "Football",
    club: "FC Breitenrain",
    status: "Actif",
    lastShoot: "Jamais",
    media: 0,
    premium: 0,
    coverage: 12,
    tone: "critical",
    instagram: "@a.wenzzzi",
    email: "wenzi.aggee@gmail.com",
    phone: "076 336 98 05",
    nextAction: "Organiser le premier shooting",
    objective: "Développer son image personnelle",
    longTerm: "S’imposer durablement au haut niveau",
  },
  {
    key: "tylian-pinton",
    name: "Tylian Pinton",
    initials: "TP",
    sport: "Basketball",
    club: "BBC Cossonay",
    status: "Actif",
    lastShoot: "12.07.2026",
    media: 84,
    premium: 9,
    coverage: 76,
    tone: "solid",
    instagram: "@tylian.8",
    email: "tylianpinton25@gmail.com",
    phone: "079 820 82 89",
    nextAction: "Préparer un contenu mensuel",
    objective: "Être le meilleur scoreur U20",
    longTerm: "S’installer en équipe première",
  },
  {
    key: "raphael-monty",
    name: "Raphaël Monty",
    initials: "RM",
    sport: "Basketball",
    club: "Pully Lausanne Foxes",
    status: "Actif",
    lastShoot: "30.06.2026",
    media: 103,
    premium: 7,
    coverage: 65,
    tone: "correct",
    instagram: "@raphaelmonty_",
    email: "montyraphael246@gmail.com",
    phone: "076 412 38 97",
    nextAction: "Planifier un portrait terrain",
    objective: "Être meilleur scoreur du championnat U20",
    longTerm: "Atteindre le niveau professionnel",
  },
];
