import type { MediaLot } from "@/types/media";

export const demoMedia: MediaLot[] = [
  {
    date: "02.08.2026",
    athlete: "Anastacia Fischer",
    sport: "Badminton",
    mediaType: "Photos + vidéos",
    event: "Camp intensif",
    place: "Fribourg",
    totalFiles: 128,
    vertical: 52,
    horizontal: 68,
    square: 8,
    premiumTotal: 18,
    filesUsed: 36,
    filesRemaining: 92,
    premiumUsed: 4,
    premiumRemaining: 14,
    favorites: 11,
    videos: 8,
    source: "Sébastien Mory",
    driveLink: "",
    lastUse: "05.08.2026",
    associatedContent: "Story camp",
    rights: "KLIQUE + athlète",
    notes: "",
  },
  {
    date: "18.03.2026",
    athlete: "Loan Cueto",
    sport: "Tennis",
    mediaType: "Photos",
    event: "Portrait KLIQUE",
    place: "Bulle",
    totalFiles: 286,
    vertical: 154,
    horizontal: 132,
    square: 0,
    premiumTotal: 12,
    filesUsed: 248,
    filesRemaining: 38,
    premiumUsed: 8,
    premiumRemaining: 4,
    favorites: 16,
    videos: 0,
    source: "Sébastien Mory",
    driveLink: "",
    lastUse: "22.07.2026",
    associatedContent: "Portrait",
    rights: "KLIQUE + athlète",
    notes: "À renouveler",
  },
];
