import { breakpoints } from "../breakpoints";
import { animations, keyframes } from "../animations";
import { tokenRef } from "./token-reference";

const t = tokenRef;

export const kliqueTailwindTheme = {
  extend: {
    colors: {
      primary: {
        50: t("color-palette-Primary-50"),
        100: t("color-palette-Primary-100"),
        200: t("color-palette-Primary-200"),
        300: t("color-palette-Primary-300"),
        400: t("color-palette-Primary-400"),
        500: t("color-palette-Primary-500"),
        600: t("color-palette-Primary-600"),
        700: t("color-palette-Primary-700"),
        800: t("color-palette-Primary-800"),
        900: t("color-palette-Primary-900"),
      },
      accent: {
        50: t("color-palette-Accent-50"),
        100: t("color-palette-Accent-100"),
        200: t("color-palette-Accent-200"),
        300: t("color-palette-Accent-300"),
        400: t("color-palette-Accent-400"),
        500: t("color-palette-Accent-500"),
        600: t("color-palette-Accent-600"),
        700: t("color-palette-Accent-700"),
        800: t("color-palette-Accent-800"),
        900: t("color-palette-Accent-900"),
      },
      neutral: {
        0: t("color-palette-Neutral-0"),
        50: t("color-palette-Neutral-50"),
        100: t("color-palette-Neutral-100"),
        200: t("color-palette-Neutral-200"),
        300: t("color-palette-Neutral-300"),
        400: t("color-palette-Neutral-400"),
        500: t("color-palette-Neutral-500"),
        600: t("color-palette-Neutral-600"),
        700: t("color-palette-Neutral-700"),
        800: t("color-palette-Neutral-800"),
        900: t("color-palette-Neutral-900"),
        950: t("color-palette-Neutral-950"),
      },
      success: {
        50: t("color-palette-Success-50"),
        100: t("color-palette-Success-100"),
        200: t("color-palette-Success-200"),
        300: t("color-palette-Success-300"),
        400: t("color-palette-Success-400"),
        500: t("color-palette-Success-500"),
        600: t("color-palette-Success-600"),
        700: t("color-palette-Success-700"),
        800: t("color-palette-Success-800"),
        900: t("color-palette-Success-900"),
      },
      warning: {
        50: t("color-palette-Warning-50"),
        100: t("color-palette-Warning-100"),
        200: t("color-palette-Warning-200"),
        300: t("color-palette-Warning-300"),
        400: t("color-palette-Warning-400"),
        500: t("color-palette-Warning-500"),
        600: t("color-palette-Warning-600"),
        700: t("color-palette-Warning-700"),
        800: t("color-palette-Warning-800"),
        900: t("color-palette-Warning-900"),
      },
      error: {
        50: t("color-palette-Error-50"),
        100: t("color-palette-Error-100"),
        200: t("color-palette-Error-200"),
        300: t("color-palette-Error-300"),
        400: t("color-palette-Error-400"),
        500: t("color-palette-Error-500"),
        600: t("color-palette-Error-600"),
        700: t("color-palette-Error-700"),
        800: t("color-palette-Error-800"),
        900: t("color-palette-Error-900"),
      },
      info: {
        50: t("color-palette-Info-50"),
        100: t("color-palette-Info-100"),
        200: t("color-palette-Info-200"),
        300: t("color-palette-Info-300"),
        400: t("color-palette-Info-400"),
        500: t("color-palette-Info-500"),
        600: t("color-palette-Info-600"),
        700: t("color-palette-Info-700"),
        800: t("color-palette-Info-800"),
        900: t("color-palette-Info-900"),
      },
      ui: {
        background: t("color-background"),
        surface: t("color-surface"),
        surfaceSecondary: t("color-surfaceSecondary"),
        surfaceHover: t("color-surfaceHover"),
        border: t("color-border"),
        borderStrong: t("color-borderStrong"),
        textPrimary: t("color-textPrimary"),
        textSecondary: t("color-textSecondary"),
        textMuted: t("color-textMuted"),
        link: t("color-link"),
        focus: t("color-focus"),
        overlay: t("color-overlay"),
      },
    },
    fontFamily: {
      sans: [t("typography-families-sans")],
      body: [t("typography-families-body")],
      mono: [t("typography-families-mono")],
    },
    fontSize: {
      xs: [t("typography-sizes-xs"), { lineHeight: t("typography-lineHeights-normal") }],
      sm: [t("typography-sizes-sm"), { lineHeight: t("typography-lineHeights-normal") }],
      base: [t("typography-sizes-md"), { lineHeight: t("typography-lineHeights-normal") }],
      lg: [t("typography-sizes-lg"), { lineHeight: t("typography-lineHeights-relaxed") }],
      xl: [t("typography-sizes-xl"), { lineHeight: t("typography-lineHeights-relaxed") }],
      "2xl": [t("typography-sizes-2xl"), { lineHeight: t("typography-lineHeights-snug") }],
      "3xl": [t("typography-sizes-3xl"), { lineHeight: t("typography-lineHeights-tight") }],
      "4xl": [t("typography-sizes-4xl"), { lineHeight: t("typography-lineHeights-tight") }],
      "5xl": [t("typography-sizes-5xl"), { lineHeight: t("typography-lineHeights-tight") }],
    },
    spacing: {
      0: t("spacing-0"),
      1: t("spacing-1"),
      2: t("spacing-2"),
      3: t("spacing-3"),
      4: t("spacing-4"),
      5: t("spacing-5"),
      6: t("spacing-6"),
      8: t("spacing-8"),
      10: t("spacing-10"),
      12: t("spacing-12"),
      16: t("spacing-16"),
      20: t("spacing-20"),
      24: t("spacing-24"),
      32: t("spacing-32"),
    },
    borderRadius: {
      none: t("radius-none"),
      xs: t("radius-xs"),
      sm: t("radius-sm"),
      md: t("radius-md"),
      lg: t("radius-lg"),
      xl: t("radius-xl"),
      "2xl": t("radius-2xl"),
      full: t("radius-full"),
    },
    boxShadow: {
      none: t("shadow-none"),
      xs: t("shadow-xs"),
      sm: t("shadow-sm"),
      md: t("shadow-md"),
      lg: t("shadow-lg"),
      xl: t("shadow-xl"),
      focus: t("shadow-focus"),
    },
    zIndex: {
      base: t("layer-zIndex-base"),
      content: t("layer-zIndex-content"),
      sticky: t("layer-zIndex-sticky"),
      dropdown: t("layer-zIndex-dropdown"),
      overlay: t("layer-zIndex-overlay"),
      modal: t("layer-zIndex-modal"),
      popover: t("layer-zIndex-popover"),
      toast: t("layer-zIndex-toast"),
      tooltip: t("layer-zIndex-tooltip"),
    },
    screens: {
      xs: breakpoints.xs,
      sm: breakpoints.sm,
      md: breakpoints.md,
      lg: breakpoints.lg,
      xl: breakpoints.xl,
      "2xl": breakpoints["2xl"],
    },
    keyframes,
    animation: animations,
    transitionDuration: {
      instant: t("motion-duration-instant"),
      fast: t("motion-duration-fast"),
      normal: t("motion-duration-normal"),
      slow: t("motion-duration-slow"),
      slower: t("motion-duration-slower"),
    },
    transitionTimingFunction: {
      ease: t("motion-easing-ease"),
      "ease-in": t("motion-easing-ease-in"),
      "ease-out": t("motion-easing-ease-out"),
      "ease-in-out": t("motion-easing-ease-in-out"),
      standard: t("motion-easing-standard"),
      emphasized: t("motion-easing-emphasized"),
      decelerate: t("motion-easing-decelerate"),
      accelerate: t("motion-easing-accelerate"),
    },
  },
} as const;
